### ISSUE TITLE
Child with same mixin

### ISSUE THREAD

**Issue by luckyraul** [KyleAMathews/react-component-width-mixin#2]
If you have parent and child with your mixin and you showing/hiding block inside child you don't have fallback to mobile or table if child's block mounted

parent

```
mixins: [componentWidthMixin],
render: function () {
        console.info('PARENT: ' + this.state.componentWidth);
        if(this.state.componentWidth > 600){
            return (<Desktop/>);
        }
        if(this.state.componentWidth > 400){
            return (<Tablet/>);
        }
        return (<Mobile />);
    }
```

and child

```
mixins: [componentWidthMixin],
render: function () {
        console.info('CHILD: '+ this.state.componentWidth);
        if(this.state.componentWidth > 1050){
            return <div>EXTRA Desktop</div>;
        }
        return <div>Desktop</div>;
    }
```

**Comment by KyleAMathews** [comment]
Can you copy/paste what's getting outputted to the console for the parent and child from this.state.componentWidth at different sizes and as you're toggling the child. Not sure I understand what's happening.

**Comment by luckyraul** [comment]
Firstly If you load with width: 1033px you get

```
PARENT: 1033
CHILD: 1033
```

and **DESKTOP** text on screen and if you resizing to bigger screen only **child** change log consequently appears and on 1050px you get **Extra desktop**.
Otherwise if you stared decreasing screen size from 1033 you will always have **DESKTOP** text and only changing **child** log. Even if you change up to 1px width.
In both situations you don't have any parent log, except on page loading.

**Comment by luckyraul** [comment]
Secondly if you load on small size (smaller then desktop) you can switch between mobile and tablet easily with both direction. You got only **parent** logs until you expand to desktop. After that you can not return to tablet or mobile, and only **child** logs

**Comment by luckyraul** [comment]
Am I clear?

**Comment by KyleAMathews** [comment]
Strange... I'm not going to have time to debug this for a while. If you can find the problem, I'd really appreciate a PR!

**Comment by luckyraul** [comment]
I'll try.

**Comment by luckyraul** [comment]
inside element-resize-event library

there is `if (!element.__resizeListeners__)` which cheks for listeners. 
So on child loading - listeners is not attached since there is another listener. And there is no resize-sensor class in dom

And I get noticed that the dom element passing through mixin is the same.
